const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');
const db = require('../config/db');
const auth = require('../middleware/auth');

// GET EXPENSE REPORT
router.get('/expenses', auth, async (req, res) => {
    try {
        const userId = req.user.id;
        const [expenses] = await db.execute('SELECT * FROM expenses WHERE user_id = ? ORDER BY expense_date DESC', [userId]);

        const doc = new PDFDocument({ margin: 50 });

        // Set Headers for Download
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', 'attachment; filename=Expense_Report.pdf');

        doc.pipe(res);

        // --- PDF GENERATION ---

        // Header
        doc.fontSize(20).text('FARM CENTRAL', { align: 'center' });
        doc.fontSize(12).text('Professional Financial Statement', { align: 'center' });
        doc.moveDown();
        doc.text(`Generated for: ${req.user.username}`);
        doc.text(`Date: ${new Date().toLocaleDateString()}`);
        doc.moveDown();

        // Table Header
        const tableTop = 150;
        doc.font('Helvetica-Bold');
        doc.text('Date', 50, tableTop);
        doc.text('Category', 150, tableTop);
        doc.text('Description', 280, tableTop);
        doc.text('Amount (INR)', 450, tableTop);

        doc.moveTo(50, tableTop + 15).lineTo(550, tableTop + 15).stroke();
        doc.font('Helvetica');

        // Table Rows
        let y = tableTop + 30;
        let total = 0;

        expenses.forEach(item => {
            const amount = Number(item.amount);
            total += amount;

            if (y > 700) { doc.addPage(); y = 50; } // Auto-paging

            doc.text(new Date(item.expense_date).toLocaleDateString(), 50, y);
            doc.text(item.category, 150, y);
            doc.text(item.description, 280, y, { width: 150, ellipsis: true });
            doc.text(amount.toFixed(2), 450, y);

            y += 20;
        });

        // Total
        doc.moveDown();
        doc.moveTo(50, y).lineTo(550, y).stroke();
        doc.font('Helvetica-Bold').fontSize(14);
        doc.text(`TOTAL EXPENSES: INR ${total.toFixed(2)}`, 50, y + 10, { align: 'right' });

        // Footer
        doc.fontSize(10).text('Generated by Farm Central System', 50, 750, { align: 'center', width: 500 });

        doc.end();

    } catch (err) {
        console.error(err);
        res.status(500).send("Report Generation Failed");
    }
});

module.exports = router;
